### ISSUE TITLE
Output.yaml is Blank

### ISSUE THREAD

**Issue by justcflt** [injectedfusion/dynamic_inventory_generator#11]
Hi,

Not really a programmer, just here trying it out. Also my first time doing anything on GitHub. When I run parser.py it creates the output.yaml file, but it is blank. Probably a mistake on my part, would appreciate any help getting it to work. When I run test.parser.py I get the below output. Maybe related?  Please feel free to close this issue and do nothing with it.

Traceback (most recent call last):
  File "test_parser.py", line 10, in <module>
    print(reader())
NameError: name 'reader' is not defined

**Comment by injectedfusion** [comment]
> Hi,
> 
> Not really a programmer, just here trying it out. Also my first time doing anything on GitHub. When I run parser.py it creates the output.yaml file, but it is blank. Probably a mistake on my part, would appreciate any help getting it to work. When I run test.parser.py I get the below output. Maybe related? Please feel free to close this issue and do nothing with it.
> 
> Traceback (most recent call last):
> File "test_parser.py", line 10, in
> print(reader())
> NameError: name 'reader' is not defined

@justcflt I have to admit that the test.parser.py isn't fully working yet. I know it's poor practice to not have a working test script, but it' just something I haven't gotten around to yet. Only parser.py is working.

**Comment by nellshamrell** [comment]
Hi @justcflt! I just added some enhancements that should help with this (I'm also happy to jump on a call to walk you through using the script). You can get the latest changes either by deleting your copy of this repo and recloning or, within your local copy of this repo:

```bash
$ git fetch origin
$ git rebase origin/master
```

Please let us know if you run into more issues!
